### ISSUE TITLE
Configure issue lapack

### ISSUE THREAD

**Issue by dblanm** [edrosten/fast-er#2]
Hi there!

First of all thanks for this incredible library!

I am getting the following issue when using
`
CXX=g++-7  ./configure
`
I have already installed TooN, libCVD and libGvars3.

Initially, I used in my system g++5 but configured all the installations with the flag CXX=g++-7.
Since I got that error, I switched my gcc and g++ system to g++-7 and reinstalled liblapack, and still get the same issue.

Any idea where is the error coming from?
<details><summary>Here the ./configure trace</summary><p>

```
checking for gawk... no
checking for mawk... mawk
checking whether the C++ compiler works... yes
checking for C++ compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C++ compiler... yes
checking whether g++-7 accepts -g... yes
checking if compiler flag -Wall works... yes
checking if compiler flag -Wextra works... yes
checking if compiler flag -W works... yes
checking how to run the C++ preprocessor... g++-7 -E
checking for grep that handles long lines and -e... /bin/grep
checking for egrep... /bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking cvd/image_io.h usability... yes
checking cvd/image_io.h presence... yes
checking for cvd/image_io.h... yes
checking libCVD... yes
checking for dgetri_ in -llapack... no
configure: error: Lapack support missing. Please install  LAPACK

```

**Comment by edrosten** [comment]
Hi,

did you install liblapack-dev? If so, can you post the config.log file? That has more detailed information in it.

**Comment by edrosten** [comment]
On Fri, 19 Oct 2018, 09:20 David Mulero, <notifications@github.com> wrote:

> Hi again,
>
> Well I finally managed to solve the *configure* issue. I did have
> liblapack-dev installed, so what I did is look into the config.log file and
> it seemed that the libCVD configuration was wrong.
>
> I basically had to remove the libcvd folder, configure and make it again.
> I used the
> The "CXX=g++-7 ./configure" step was successful this time.
>
> However, when I tried to compile, it gave me the following error:
> learn_detector.cc:68:10: fatal error: cvd/random.h: No such file or
> directory
>
Looks like your version of libcvd is too new. I did some major cleanups a
while back and looks like I  didn't update this code. Can you try an older
version?

I'm on travel at the moment, I can look at updating this code when I return.

**Comment by edrosten** [comment]
Big list of bugs for me to fix :)

This one's due to the linker being much more aggressive about removing
libraries than before.

Can you add -pthread to the linker line?


A cheaty hack is to set the compiler to
CXX="g++-7 -pthread"

**Comment by dblanm** [comment]
Yes I did and it built successfully.
Thanks!
